# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis
sudo: required
language: r

before_install:
  - cd ./platereading

env:
  - WARNINGS_ARE_ERRORS=1

notifications:
  email:
    on_success: change
    on_failure: change
